# Chinese-MNIST (Kaggle) preprocessing + SURGE workflow config

# No longer needed BECAUSE I already converted the dataset to flattened csv
# conversion:
#   index_csv_path: C:/Users/Bipo1/Downloads/Kaggle Chinese MNIST Data/chinese_mnist.csv
#   images_dir: C:/Users/Bipo1/Downloads/Kaggle Chinese MNIST Data/data/data
#   output_csv_path: C:/Users/Bipo1/Downloads/Kaggle Chinese MNIST Data/chinese_mnist_flattened.csv
#   label_column: value
#   filename_template: input_{suite_id}_{sample_id}_{code}.jpg
#   normalize_features: true
#   target_size: [64, 64]
#   feature_prefix: pixel_
#   verbose: true

workflow:
  dataset_path: C:/Users/Bipo1/Downloads/Kaggle Chinese MNIST Data/chinese_mnist_flattened.csv #comment out this line if using conversion block
  dataset_format: csv
  metadata_overrides:
    outputs: [value]
  task_type: unsupervised

  test_fraction: 0.2
  val_fraction: 0.1
  standardize_inputs: false
  standardize_outputs: false
  seed: 42

  output_dir: .
  run_tag: chinese_mnist_kaggle
  overwrite_existing_run: true
  predictions_format: parquet

  models:
    - key: sklearn.pca
      name: PCA
      params:
        n_components: 64
        svd_solver: auto
        whiten: true
      store_predictions: true
